---
- name: netology-ml
  hosts: all
  become: yes

  vars:
    packages:
      - net_tools
      - git
      - tree
      - htop
      - mc
      - vim
    destination: /home/text.txt

  tasks:
  - name: Ping my servers
    ping:

  - name: Copy Files
    copy: src=test.txt dest={{ destination }} mode=0777

  - name: Install packages
    apt:
      name: "{{packages}}"
      state: latest

  - name: Update apt packages
    apt:
      update_cache: yes

  - name: Group create
    group:
      name: "{{item}}"
      state: present
    loop:
       - devops_1
       - test_1

  - name: Create user Devops
    user:
      name: devops_1
      group: devops_1

  - name: Create user Test
    user:
      name: test_1
      group: test_1

